import React from 'react';
import { 
  DownloadCloud, 
  FileText, 
  CheckCircle2, 
  ShieldCheck, 
  ExternalLink,
  Layers,
  Sparkles
} from 'lucide-react';
import { DOWNLOAD_MATCHING_URL, DOWNLOAD_CANDIDATES_URL } from '../services/api';

export const DownloadView: React.FC = () => {
  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-xl font-bold text-white flex items-center gap-2">
          <DownloadCloud className="h-5 w-5 text-emerald-400" />
          Phase 15 — Download Submission Output Files
        </h2>
        <p className="text-xs text-slate-400 mt-1">
          Download finalized entity resolution outputs ready for hackathon evaluation and deployment.
        </p>
      </div>

      {/* Download Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* matching_results.tsv Card */}
        <div className="p-6 rounded-2xl glass-panel border border-brand-500/30 bg-brand-950/20 shadow-xl space-y-4 flex flex-col justify-between">
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full bg-brand-500/20 text-brand-300 border border-brand-500/30">
                Primary Scored Submission
              </span>
              <span className="text-xs font-mono text-emerald-400 font-semibold flex items-center gap-1">
                <CheckCircle2 className="h-3.5 w-3.5" /> Validated
              </span>
            </div>

            <div>
              <h3 className="text-base font-bold text-white font-mono">matching_results.tsv</h3>
              <p className="text-xs text-slate-300 mt-1">
                Final resolved match pairs generated by the reusable supervised model with optimal decision threshold.
              </p>
            </div>

            <div className="p-3 rounded-xl bg-slate-900/60 border border-slate-800 text-xs font-mono text-slate-400 space-y-1">
              <p className="text-[11px] text-slate-300 font-semibold font-sans">Schema Structure:</p>
              <p className="text-brand-300">source1_entity_id &lt;tab&gt; matched_entity_ids</p>
              <p className="text-slate-500 text-[10px]">S1-10023 &lt;tab&gt; S2-49102,S3-99120</p>
            </div>
          </div>

          <a
            href={DOWNLOAD_MATCHING_URL}
            download="matching_results.tsv"
            className="w-full py-3 rounded-xl bg-gradient-to-r from-brand-600 to-indigo-600 hover:from-brand-500 hover:to-indigo-500 text-white text-xs font-bold shadow-lg shadow-brand-500/20 flex items-center justify-center gap-2 transition text-center"
          >
            <DownloadCloud className="h-4 w-4" />
            Download matching_results.tsv
          </a>
        </div>

        {/* candidate_pairs.tsv Card */}
        <div className="p-6 rounded-2xl glass-panel border border-indigo-500/30 bg-indigo-950/20 shadow-xl space-y-4 flex flex-col justify-between">
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                Blocking Candidate Set
              </span>
              <span className="text-xs font-mono text-emerald-400 font-semibold flex items-center gap-1">
                <CheckCircle2 className="h-3.5 w-3.5" /> Validated
              </span>
            </div>

            <div>
              <h3 className="text-base font-bold text-white font-mono">candidate_pairs.tsv</h3>
              <p className="text-xs text-slate-300 mt-1">
                Candidate pairs emitted during multi-pass inverted blocking (Country, First Token, 3-gram Prefix, Address Numbers).
              </p>
            </div>

            <div className="p-3 rounded-xl bg-slate-900/60 border border-slate-800 text-xs font-mono text-slate-400 space-y-1">
              <p className="text-[11px] text-slate-300 font-semibold font-sans">Schema Structure:</p>
              <p className="text-indigo-300">source1_entity_id &lt;tab&gt; candidate_entity_ids</p>
              <p className="text-slate-500 text-[10px]">S1-10023 &lt;tab&gt; S2-49102,S2-50012,S3-99120</p>
            </div>
          </div>

          <a
            href={DOWNLOAD_CANDIDATES_URL}
            download="candidate_pairs.tsv"
            className="w-full py-3 rounded-xl bg-slate-800 hover:bg-slate-700 text-white text-xs font-bold border border-slate-700 shadow-md flex items-center justify-center gap-2 transition text-center"
          >
            <DownloadCloud className="h-4 w-4" />
            Download candidate_pairs.tsv
          </a>
        </div>
      </div>

      {/* Submission Instructions */}
      <div className="p-6 rounded-2xl glass-panel border border-slate-800 space-y-3">
        <h3 className="text-sm font-bold text-white flex items-center gap-2">
          <ShieldCheck className="h-4 w-4 text-emerald-400" />
          Submission & Leaderboard Best Practices
        </h3>
        <ul className="text-xs text-slate-300 space-y-2 list-disc list-inside">
          <li>Ensure both <code>matching_results.tsv</code> and <code>candidate_pairs.tsv</code> are included in the final submission zip.</li>
          <li>Never rename column headers or convert UTF-8 TSVs into other encodings.</li>
          <li>The validator enforces that all final matches in <code>matching_results.tsv</code> are valid candidates from <code>candidate_pairs.tsv</code>.</li>
        </ul>
      </div>
    </div>
  );
};
